name       : xiccd
version    : 0.3.0
release    : 2
source     :
    - https://github.com/agalakhov/xiccd/archive/v0.3.0.tar.gz : 94dbe352ad3043079fa5edd8150318ec88f1dc87b75f69b1fced8ce2981c36a9
license    : GPL-3.0-or-later
component  : xorg.display
summary    : xiccd is a simple bridge between colord and X
description: |
    It does the following tasks:

     * Enumerates displays and register them in colord
     * Creates default ICC profiles based on EDID data
     * Applies ICC profiles provided by colord
     * Maintains user's private ICC storage directory

    It does basically the same as gnome-settings-daemon color plugin or colord-kde but does not depend on any particular desktop. It even doesn't depend on GTK so it doesn't create useless GTK3 dependency if the desktop environment is GTK2-based or vice versa. The primary goal of xiccd is providing color profile support for desktop environments other than Gnome and KDE (Xfce, LXDE and probably others) that do not support native color management yet. It is however not meant to be excuse of not adding native color management to the session daemons of them.
builddeps  :
    - pkgconfig(colord)
    - pkgconfig(xrandr)
setup      : |
    %patch -p1 < $pkgfiles/0001-Use-stateless-directories.patch
    
    %reconfigure
build      : |
    %make
install    : |
    %make_install
